version: "3.9"
services:
  app:
    image: eventlulu-app
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://root:secret@db:5432/eventlulu?sslmode=disable
      DEFAULT_PASSWORD: default_password
      SALT_ROUNDS: "12"
      NEXTAUTH_SECRET: secret
      NEXTAUTH_URL: localhost:8000/
    depends_on:
      - db
    command: "server.js"
  db:
    image: postgres:16.2-alpine3.19
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: eventlulu
    ports:
      - "5432:5432"
    volumes:
      - "eventlulu-volume:/var/lib/postgresql/data"

volumes:
  eventlulu-volume:
