services:
  app:
    image: eventlulu-app
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "8888:8888"
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      DEFAULT_PASSWORD: "${DEFAULT_PASSWORD}"
      SALT_ROUNDS: "${SALT_ROUNDS}"
      NEXTAUTH_SECRET: "${NEXTAUTH_SECRET}"
      NEXTAUTH_URL: "${NEXTAUTH_URL}"
    env_file:
      - .env
    depends_on:
      - db
    command: "server.js"
  db:
    image: postgres:16.2-alpine3.19
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - "eventlulu-volume:/var/lib/postgresql/data"

volumes:
  eventlulu-volume:
